import { Layout } from '@/components/Layout';
import { Navbar } from '@/components/Navbar';
import { TaskProvider } from '@/context/TaskContext';
import { Toaster } from '@/app/Toaster';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <TaskProvider>
          <Navbar />

          <Layout>{children}</Layout>

          <Toaster />
        </TaskProvider>
      </body>
    </html>
  );
}
